sequenceDiagram
    participant agg as Aggregator
    participant collab as Collaborator
    participant TaskRunner

    collab->>agg: get_task()
    agg-->>collab: 'task list'
    collab->>TaskRunner: do_task('query')
    TaskRunner-->>collab: 'query results'

    collab->>agg: send_task_results()
    agg-->agg: aggregate_results()
